version: '3'

services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    networks:
      - notes




networks:
  notes:
    driver: bridge
